Models/JobPosting.cs
namespace Worktastic.Models
{
    public class JobPosting
    {
        public int Id { get; set; }

        public required string JobTitle { get; set; }

        public required string JobLocation { get; set; }

        public required string JobDescription { get; set; }

        public required int Salary { get; set; }

        public required DateTime StartDate { get; set; }

        public required string CompanyName { get; set; }

        public required string ContactPhone { get; set; }

        public required string ContactMail { get; set; }

        public required string ContactWebsite { get; set; }

        public required byte[] CompanyImage { get; set; }

        public required string OwnerUserName {get;set;}
    }
}

Controllers/JobPostingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Worktastic.Data;
using Worktastic.Models;

namespace Worktastic.Controllers;

[Authorize]
public class JobPostingController : Controller
{

    private readonly ApplicationDbContext _context;

    public JobPostingController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        if (User.IsInRole("Admin"))
        {
            var jobPostingsFromDb = _context.JobPostings.ToList();
            return View(jobPostingsFromDb);
        }
        else
        {
            var jobPostingsFromDb = _context.JobPostings.Where(x => x.OwnerUserName == User.Identity!.Name).ToList();
            return View(jobPostingsFromDb);
        }

    }

    public IActionResult CreateEditJobPosting(int id)
    {
        if (id != 0)
        {
            var jobPostingFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == id);

            if (jobPostingFromDb == null)
            {
                return NotFound();
            }

            if (jobPostingFromDb!.OwnerUserName != User.Identity?.Name && !User.IsInRole("Admin"))
            {
                return Unauthorized();
            }

            return View(jobPostingFromDb);
        }

        return View();
    }

    [HttpPost]
    public IActionResult DeleteJobPostingById(int id)
    {
        if (id != 0)
        {
            var jobPostingFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == id);
            if (jobPostingFromDb != null)
            {
                _context.JobPostings.Remove(jobPostingFromDb);
                _context.SaveChanges();
                return Ok();
            }
            else
            {
                return NotFound();
            }
        }

        return NotFound();
    }


    public IActionResult CreateEditJob(JobPosting jobPosting, IFormFile file)
    {
        jobPosting.StartDate = DateTime.SpecifyKind(jobPosting.StartDate, DateTimeKind.Utc);
        jobPosting.OwnerUserName = User.Identity!.Name!;

        if (file != null)
        {
            using var ms = new MemoryStream();
            file.CopyTo(ms);
            var bytes = ms.ToArray();
            jobPosting.CompanyImage = bytes;
        }
        else
        {
            jobPosting.CompanyImage = Array.Empty<byte>();
        }

        // default int is 0
        if (jobPosting.Id == 0)
        {
            _context.JobPostings.Add(jobPosting);
        }
        else
        {
            var jobFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == jobPosting.Id);

            if (jobFromDb == null)
            {
                return NotFound();
            }

            jobFromDb.CompanyImage = jobPosting.CompanyImage;
            jobFromDb.CompanyName = jobPosting.CompanyName;
            jobFromDb.Salary = jobPosting.Salary;
            jobFromDb.ContactMail = jobPosting.ContactMail;
            jobFromDb.ContactPhone = jobPosting.ContactPhone;
            jobFromDb.ContactWebsite = jobPosting.ContactWebsite;
            jobFromDb.JobTitle = jobPosting.JobTitle;
            jobFromDb.JobDescription = jobPosting.JobDescription;
            jobFromDb.JobLocation = jobPosting.JobLocation;
            jobFromDb.StartDate = jobPosting.StartDate;
            // jobFromDb.OwnerUserName = jobPosting.OwnerUserName;
        }


        _context.SaveChanges();
        return RedirectToAction("Index");
    }
}

Views/JobPosting/CreateEditJobPosting.cshtml
@model Worktastic.Models.JobPosting

@{
    ViewData["Title"] = "Erstellen oder Bearbeiten";
}

<form asp-controller="JobPosting" asp-action="CreateEditJob" enctype="multipart/form-data">
    <div class="card">
        <div class="card-header">
            <h5>Inserat bearbeiten</h5>
        </div>
        <div class="card-body">
            <input hidden asp-for="Id" />
            <div class="row mb-3">
                <div class="col">
                    <input class="form-control" asp-for="JobTitle" type="text"
                        placeholder="Bitte trage eine Jobbezeichnung ein." />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="JobLocation" type="text"
                        placeholder="Bitte trage einen Ort ein." />
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <textarea rows="6" class="form-control" asp-for="JobDescription"
                        placeholder="Bitte trage eine ausführliche Beschreibung ein."></textarea>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <input class="form-control" asp-for="Salary" type="number"
                        placeholder="Wieviel Jahresgehalt zahlt ihr?" />
                </div>

            </div>
            <div class="row mb-3">
                <div class="col-6">
                    <div class="col-form-label">
                        Wann startet der Job?
                    </div>
                    <input class="form-control" asp-for="StartDate" type="date" placeholder="Wann startet der Job?" />
                </div>
            </div>
            <hr />
            <div class="row mb-3">
                <div class="col">
                    <input class="form-control" asp-for="CompanyName" type="text"
                        placeholder="Wie heißt deine Firma?" />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="ContactWebsite" type="text"
                        placeholder="Die Webadresse deiner Firma?" />
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <input class="form-control" asp-for="ContactPhone" type="text" placeholder="Telefonnummer." />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="ContactMail" type="email" placeholder="Email." />
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <label>Bild</label>
                    <input class="form-control" name="file" type="file"  />
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button class="btn btn-primary" type="submit">Speichern</button>
        </div>
    </div>
</form>

Views/JobPosting/Index.cshtml
@model List<JobPosting>

@{
    ViewData["Title"] = "Deine Inserate";
}

<a class="btn btn-primary" asp-controller="JobPosting" asp-action="CreateEditJobPosting">Neues Inserat anlegen</a>
<hr />
<table id="jobPostingTable" class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
        <tr>
            <th>Title</th>
            <th>Ort</th>
            <th>Firmenname</th>
            <th>Aktionen</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (JobPosting jobPosting in Model)
            {
                <tr>
                    <td>@jobPosting.JobTitle</td>
                    <td>@jobPosting.JobLocation</td>
                    <td>@jobPosting.CompanyName</td>
                    <td>
                        <a asp-route-id="@jobPosting.Id" asp-controller="JobPosting" asp-action="CreateEditJobPosting"
                            class="btn btn-warning">Edit</a>
                        @* <a asp-route-id="@jobPosting.Id" asp-controller="JobPosting" asp-action="DeleteJobPosting" class="btn
                btn-danger">Delete</a> *@
                        <button onclick="onClickedDeleteButton(@jobPosting.Id)" class="btn btn-danger">Löschen</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#jobPostingTable').DataTable();
        });

        function onClickedDeleteButton(id) {
            Swal.fire({
                title: "Möchtest du das Inserat wirklich löschen?",
                icon: "error",
                showCloseButton: true,
                focusConfirm: false,
                confirmButtonText: `Ja, löschen!`,
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("DeleteJobPostingById")",
                        data: { id: id },
                        success: function (msg) {
                            Swal.fire('Wurde gelöscht!', '', 'success').then((result) => {
                                if (result.isConfirmed) {
                                    location.reload();
                                }
                            });
                        },
                        error: function (msg) {
                            Swal.fire('Ups, etwas ist schief gelaufen!', '', 'error');
                        }
                    })

                }
            });
        }
    </script>
}